---
framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./test/**/*_test.ts"
postMerge:
  pattern: 
    - "./test/**/*_test.ts"
postRun:
     command:
        - yarn --version
tier: large
parallelism: 2
splitMode: file
version: 1.1
